language: android
android:
        components:
                - platform-tools
                - build-tools-26.0.2
                - android-26
                - extra-android-m2repository
script:
        - ./gradlew build
before_install:
        - chmod +x gradlew